In [5]:
import numpy as np
X = np.array([[84.1, -52.2], [-52.2, 130.4]])
L, A = np.linalg.eig(X)#固有値,固有ベクトル
X

array([[ 84.1, -52.2],
       [-52.2, 130.4]])

In [6]:
L

array([ 50.14691339, 164.35308661])

In [7]:
A

array([[-0.83827417,  0.54524895],
       [-0.54524895, -0.83827417]])

In [8]:
x1 = [22, 22, 18, 18, 15, 19, 19, 24, 21, 25]
x2 = [12, 8, 6, 15, 7, 9, 7, 17, 14, 11]
COV = np.cov( [x1, x2] ) # 共分散行列

In [9]:
COV

array([[ 9.34444444,  5.8       ],
       [ 5.8       , 14.48888889]])

In [10]:
L, A = np.linalg.eig(COV)

In [11]:
L

array([ 5.57187927, 18.26145407])

In [12]:
A

array([[-0.83827417, -0.54524895],
       [ 0.54524895, -0.83827417]])

In [13]:
z1 = (-A[0,1]) * (x1-np.mean(x1)) + (-A[1,1]) * (x2-np.mean(x2)) 

In [14]:
z1

array([ 2.10050705, -1.25258961, -5.11013376,  2.43433374, -5.90760645,
       -2.05006231, -3.72661064,  7.3823758 ,  3.23180643,  2.89797975])

In [15]:
x1 = [22, 22, 18, 18, 15, 19, 19, 24, 21, 25]
x2 = [12, 8, 6, 15, 7, 9, 7, 17, 14, 11]
# 標準化することで単位による誤差を無くす
x1_h = ( x1-np.mean(x1) ) / np.std(x1, ddof=1)
x2_h = ( x2-np.mean(x2) ) / np.std(x2, ddof=1)
# 共分散行列の固有値分解
COV = np.cov([x1_h, x2_h])
L, A = np.linalg.eig(COV)
# 主成分得点
z1 = A[0,0] * (x1_h-np.mean(x1_h)) + A[1,0] * (x2_h-np.mean(x2_h))
z2 = A[0,1] * (x1_h-np.mean(x1_h)) + A[1,1] * (x2_h-np.mean(x2_h))

In [16]:
L

array([1.4984639, 0.5015361])

In [17]:
A

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [18]:
z1

array([ 0.65331268, -0.08975343, -1.38655599,  0.28534275, -1.89474159,
       -0.59793903, -0.96947209,  2.04478007,  0.79352835,  1.16149828])

In [19]:
z2

array([-0.1331664 , -0.87623251, -0.32249606,  1.34940268,  0.5572226 ,
        0.00348615, -0.36804691,  0.33303148,  0.46968403, -1.01288506])