In [1]:
def jukaiki_bunseki(X, y):

 N = np.size(y) # 標本数
 Y = np.c_[y]
 X = np.c_[X, np.ones(N)]

 tmp = np.dot(X.T, X)
 r1 = np.linalg.inv(tmp)
 r2 = np.dot(X.T, Y)
 A = np.dot(r1, r2) # 係数ベクトル

 Y_hat = np.dot(X, A) # 内積 (予測値): a1*x1+a2*x2+...+b*1
 Y_hat = Y_hat[:, 0] # 0列のみを指定 (行列→ベクトル)

 C = np.corrcoef(Y_hat, y)[0,1]
 R2 = np.sum( (Y_hat-np.mean(y))**2 ) / np.sum( (y-np.mean(y))**2 )

 return A, C, R2

In [3]:
import numpy as np
x1=[3,5,2,4,4,5,1,1,4,4,5,2,5,1,2]
x2=[3,4,2,4,4,4,3,2,4,3,4,2,5,2,2]
x3=[4,2,2,3,2,2,3,3,5,4,2,2,1,4,2]
y=[3,2,1,2,3,1,3,1,5,3,3,1,4,1,1]
N = np.size(y)
X = np.c_[x1, x2, x3]
A, C, R2 = jukaiki_bunseki(X, y)
print(A)
print(C)
print(R2)


[[-0.27524303]
 [ 1.33115731]
 [ 0.50904704]
 [-2.5036543 ]]
0.8272730306826344
0.6843806672948266


In [4]:
x1_h = (x1-np.mean(x1)) / np.std(x1, ddof=1)
x2_h = (x2-np.mean(x2)) / np.std(x2, ddof=1)
x3_h = (x3-np.mean(x3)) / np.std(x3, ddof=1)
y_h = (y-np.mean(y)) / np.std(y, ddof=1)
X_h = np.c_[x1_h, x2_h, x3_h]
A, C, R2 = jukaiki_bunseki(X_h, y_h)
print(A)
print(C)
print(R2)


[[-3.37102487e-01]
 [ 1.05481680e+00]
 [ 4.37416899e-01]
 [ 2.25346780e-16]]
0.827273030682634
0.6843806672948303


In [5]:
A, C, R2 = jukaiki_bunseki( np.c_[x1_h, x3_h], y_h)
print(A)
print(C)
print(R2)

[[5.87835518e-01]
 [4.58861357e-01]
 [1.26653055e-16]]
0.6461592625119486
0.4175217925299851


In [7]:
A, C, R2 = jukaiki_bunseki(x1_h, x2_h)
print(A)
print(C)
print(R2)

[[ 8.71648250e-01]
 [-8.08632883e-17]]
0.8716482500611272
0.759770671834625


In [11]:
A, C, R2 = jukaiki_bunseki(x1_h, x3_h)
print(A)
print(C)
print(R2)

[[-2.56886475e-01]
 [-5.07245884e-17]]
0.2568864750256222
0.0659906610510896
